export default function Head() {
  return (
    <>
      <title>Blockheath</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by Blockheath Team" />
      <link rel="icon" href="/images/fav.png" />
    </>
  );
}
